apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name  : cluster-kap
  region: us-east-1

nodeGroups:
  - name: WNode-1
    instanceType : t2.micro
    desiredCapacity     : 1
    labels:
      nodegroup-type: nodes 
      env           : kubernetes
  - name: WNode-2
    instanceType : t2.micro
    desiredCapacity     : 1
    labels:
      nodegroup-type: nodes 
      env           : kubernetes