apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name  : kap-clu
  region: us-east-1

nodeGroups:
  - name: worker1
    instanceType : t2.small
    desiredCapacity     : 1
    privateNetworking: true
    labels:
      nodegroup-type: nodes 
      env           : kubernetes     
  - name          : worker-nodes-group-2
    instanceType : t2.small
    desiredCapacity     : 1
    privateNetworking: true
    labels:
      nodegroup-type: nodes
      env           : kubernetes