apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    env  : prod
    app  : main
    tier : frontend
    owner: Oleksandr_Kashuba
spec:
  containers:         
    - name: containers-api
      image: kapalulz/k8sphp
      ports:
        - containerPort: 80